name: Build voor macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Repository klonen
      uses: actions/checkout@v3

    - name: Installeer dependencies (voorbeeld met Homebrew)
      run: |
        brew install cmake

    - name: Build uitvoeren
      run: |
        mkdir build
        cd build
        cmake ..
        make
